### ISSUE TITLE
Network error when trying to fetch models

### ISSUE THREAD

**Issue by sammcj** [TC-Zheng/ActuosusAI#20]
When the app is first loaded, this error pops up:

<img width="408" alt="image" src="https://github.com/user-attachments/assets/41a27275-0e28-4c9f-82e3-846b503f09dc">

It also occurs whenever I search for a model.

Logs from the frontend container:

```
> frontend@0.1.0 dev
> next dev

  ▲ Next.js 14.2.15
  - Local:        http://localhost:3000
  - Experiments (use with caution):
    · typedRoutes

 ✓ Starting...
 ✓ Ready in 1255ms
 ○ Compiling /models ...
 ✓ Compiled /models in 2.2s (896 modules)
 GET /models 200 in 2307ms
 ✓ Compiled in 129ms (437 modules)
 GET /models 200 in 19ms
npm error path /frontend
npm error command failed
npm error signal SIGTERM
npm error command sh -c next dev
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-04T04_56_38_554Z-debug-0.log

> frontend@0.1.0 dev
> next dev

  ▲ Next.js 14.2.15
  - Local:        http://localhost:3000
  - Experiments (use with caution):
    · typedRoutes

 ✓ Starting...
 ✓ Ready in 1078ms

< this is when I loaded the app in the browser>

 ○ Compiling /models ...
 ✓ Compiled /models in 805ms (883 modules)
 GET /models 200 in 958ms
 ✓ Compiled in 130ms (437 modules)
```

The backend logs don't show any failures.

My docker compose:

```yaml
...
services:
  &name actuosus_backend:
    <<: [*ai-common, *restart, *secopts, *gpu]
    container_name: *name
    hostname: *name
    profiles:
      - actuosus
    build:
      context: https://github.com/TC-Zheng/ActuosusAI.git#main
      dockerfile: Dockerfile.gpu
    command: [ "poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    volumes:
      - /mnt/llm/actuosusai/local_storage:/local_storage
      - /mnt/llm/actuosusai/git/backend:/backend
    ports:
      - 8000
    env_file:
      - ./env/.actuosusai.env
    networks:
      - traefik
    labels:
      traefik.enable: false
      org.hotio.pullio.update: true

  &name actuosus_frontend:
    <<: [*ai-common, *restart, *secopts]
    container_name: actuosus_frontend
    hostname: actuosus_frontend
    profiles:
      - actuosus
    build:
      context: https://github.com/TC-Zheng/ActuosusAI.git#main:frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    volumes:
      - /mnt/llm/actuosusai/git/frontend/app:/frontend/app
    ports:
      - 3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - actuosus_backend
    networks:
      - traefik
    labels:
      traefik.enable: true
      org.hotio.pullio.update: true
      traefik.http.routers.actuosus_frontend.rule: Host(`actuosus.my.internal.domain`)
      traefik.http.routers.actuosus_frontend.tls.certresolver: le
      traefik.http.routers.actuosus_frontend.entrypoints: websecure
      traefik.http.routers.actuosus_frontend.tls.domains[0].main: "*.my.internal.domain"
      traefik.http.routers.actuosus_frontend.service: actuosus_frontend-service
      traefik.http.services.actuosus_frontend-service.loadbalancer.server.port: 3000
```
